import React, { useCallback, useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Check, Minus, X } from 'lucide-react-native';
import { Card, Empty, Heading, Row, Screen } from '../components';
import { getAttendanceSummaries, getSetting, getTodayAttendance, markAttendance } from '../db';
import { AppTheme } from '../theme';
import { AttendanceStatus, AttendanceSummary, TodayAttendance } from '../types';

const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
export function AttendanceScreen({ theme }: { theme: AppTheme }) {
  const [today, setToday] = useState<TodayAttendance[]>([]); const [summaries, setSummaries] = useState<AttendanceSummary[]>([]); const [threshold, setThreshold] = useState(75);
  const refresh = useCallback(async () => { const [classes, all, saved] = await Promise.all([getTodayAttendance(new Date().getDay(), localDate()), getAttendanceSummaries(), getSetting('attendance_threshold')]); setToday(classes); setSummaries(all); setThreshold(Number(saved) || 75); }, []);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  const mark = async (subjectId: number, timetableSlotId: number, status: AttendanceStatus) => { await markAttendance(localDate(), subjectId, timetableSlotId, status); await refresh(); };
  return <Screen theme={theme}><Heading theme={theme} eyebrow={new Date().toLocaleDateString([], { weekday:'long', month:'short', day:'numeric' })}>Attendance</Heading><View style={{ gap:9 }}><Text style={{ color:theme.colors.text, fontWeight:'800', fontSize:17 }}>Today’s classes</Text>{today.length ? today.map((item) => <Card key={item.timetable_slot_id} theme={theme}><Row theme={theme} title={item.name} subtitle={`${item.start_time}–${item.end_time}${item.room ? ` · ${item.room}` : ''}${item.attendance_status ? ' · Marked' : ''}`}/><View style={{ flexDirection:'row', gap:7 }}><StatusButton theme={theme} label="Present" selected={item.attendance_status==='present'} color={theme.colors.positive} icon={<Check size={15} color={item.attendance_status==='present'?'#fff':theme.colors.positive}/>} onPress={() => void mark(item.id,item.timetable_slot_id,'present')}/><StatusButton theme={theme} label="Absent" selected={item.attendance_status==='absent'} color={theme.colors.danger} icon={<X size={15} color={item.attendance_status==='absent'?'#fff':theme.colors.danger}/>} onPress={() => void mark(item.id,item.timetable_slot_id,'absent')}/><StatusButton theme={theme} label="Cancelled" selected={item.attendance_status==='cancelled'} color={theme.colors.muted} icon={<Minus size={15} color={item.attendance_status==='cancelled'?'#fff':theme.colors.muted}/>} onPress={() => void mark(item.id,item.timetable_slot_id,'cancelled')}/></View></Card>) : <Empty theme={theme} title="No classes today" detail="Today’s subjects come directly from your weekly timetable."/>}</View><View style={{ gap:9 }}><Text style={{ color:theme.colors.text, fontWeight:'800', fontSize:17 }}>Lowest attendance first</Text><Text style={{ color:theme.colors.muted, fontSize:13 }}>Cancelled classes are recorded but do not lower your percentage. Minimum target: {threshold}%.</Text>{summaries.map((item) => { const low=item.percentage!==null&&item.percentage<threshold; return <Card key={item.id} theme={theme} style={low?{borderColor:theme.colors.danger}:undefined}><Row theme={theme} title={item.name} subtitle={item.total_count ? `${item.present_count} present · ${item.absent_count} absent · ${item.cancelled_count} cancelled` : 'No counted classes yet'} right={<Text style={{ fontSize:22, fontWeight:'800', color:low?theme.colors.danger:item.percentage===null?theme.colors.muted:theme.colors.positive }}>{item.percentage===null?'—':`${item.percentage}%`}</Text>}/></Card>; })}</View></Screen>;
}
function StatusButton({ theme,label,selected,color,icon,onPress }:{ theme:AppTheme;label:string;selected:boolean;color:string;icon:React.ReactNode;onPress:()=>void }) { return <Pressable onPress={onPress} style={({pressed})=>({ flex:1, minHeight:39, borderRadius:11, alignItems:'center', justifyContent:'center', flexDirection:'row', gap:4, backgroundColor:selected?color:theme.colors.surfaceSoft, opacity:pressed?.75:1 })}><>{icon}</><Text style={{ color:selected?'#fff':theme.colors.text, fontWeight:'800', fontSize:10 }}>{label}</Text></Pressable>; }
