import React, { useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { BookOpen, X } from 'lucide-react-native';
import { Button, Card, Heading, Input, Screen } from '../components';
import { addSubject, setSetting } from '../db';
import { AppTheme, palette } from '../theme';

const starterSubjects = ['Data Structures', 'Database Systems', 'Software Engineering', 'Computer Networks', 'Operating Systems'];
export function OnboardingScreen({ theme, done }: { theme: AppTheme; done: () => void }) {
 const [name, setName] = useState(''); const [semester, setSemester] = useState('5th Semester'); const [subject, setSubject] = useState(''); const [subjects, setSubjects] = useState(starterSubjects);
 const finish = async () => { if (!name.trim()) return Alert.alert('A name helps personalize StudyHub'); await setSetting('student_name', name.trim()); await setSetting('semester', semester.trim() || '5th Semester'); await Promise.all(subjects.map((s, i) => addSubject({ name: s, code: null, teacher: null, color: [palette.clay, palette.moss, '#5878A6', '#946D42', '#A05773'][i % 5] ?? palette.clay }))); await setSetting('onboarded', 'true'); done(); };
 return <Screen theme={theme}><View style={{ height: 22 }}/><View style={{ gap: 11 }}><View style={{ width: 58, height: 58, borderRadius: 18, backgroundColor: theme.colors.accentSoft, alignItems: 'center', justifyContent: 'center' }}><BookOpen color={theme.colors.accent} size={30}/></View><Heading theme={theme} eyebrow="Your personal study space">Welcome to StudyHub</Heading><Text style={{ color: theme.colors.muted, lineHeight: 22 }}>A calm place for classes, deadlines, notes, and focused questions—kept entirely on your phone.</Text></View><Card theme={theme}><Input theme={theme} label="What should we call you?" value={name} onChangeText={setName} placeholder="Your first name"/><Input theme={theme} label="Current semester" value={semester} onChangeText={setSemester} placeholder="e.g. Comsats 5th Semester"/></Card><Card theme={theme}><Text style={{ color: theme.colors.text, fontWeight: '800', fontSize: 16 }}>Your courses</Text><Text style={{ color: theme.colors.muted, fontSize: 13 }}>We added common starter courses—remove or add anything.</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{subjects.map((item) => <View key={item} style={{ flexDirection: 'row', gap: 5, alignItems: 'center', borderRadius: 99, paddingVertical: 7, paddingLeft: 11, paddingRight: 8, backgroundColor: theme.colors.surfaceSoft }}><Text style={{ color: theme.colors.text, fontWeight: '700', fontSize: 12 }}>{item}</Text><X size={14} color={theme.colors.muted} onPress={() => setSubjects(subjects.filter(s => s !== item))}/></View>)}</View><View style={{ flexDirection: 'row', gap: 8 }}><View style={{ flex: 1 }}><Input theme={theme} value={subject} onChangeText={setSubject} placeholder="Add a course"/></View><Button theme={theme} label="Add" onPress={() => { if (subject.trim()) { setSubjects([...subjects, subject.trim()]); setSubject(''); } }} variant="secondary"/></View></Card><Button theme={theme} label="Create my study space" onPress={finish}/></Screen>;
}
