import React, { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { Trash2 } from 'lucide-react-native';
import { Button, Card, Heading, Input, Screen } from '../components';
import { importSemesterSubjects } from '../db';
import { AppTheme } from '../theme';
import { GradeDraft, LetterGrade, gradePoints } from '../types';
import { GradeChoices } from './GpaScreen';

type EditableGrade = GradeDraft & { key:string };
export function TranscriptReviewScreen({theme,navigation,route}:{theme:AppTheme;navigation:any;route:any}){const [rows,setRows]=useState<EditableGrade[]>((route.params.rows as GradeDraft[]).map((r,i)=>({...r,key:String(i)})));const [saving,setSaving]=useState(false);const update=(key:string,patch:Partial<EditableGrade>)=>setRows(current=>current.map(r=>r.key===key?{...r,...patch}:r));const confirm=async()=>{const valid=rows.map(r=>({subject_name:r.subject.trim(),credit_hours:Number(r.credit_hours),grade:r.grade.toUpperCase() as LetterGrade,grade_kind:'actual' as const}));if(valid.some(r=>!r.subject_name||!Number.isFinite(r.credit_hours)||r.credit_hours<=0||!(r.grade in gradePoints)))return Alert.alert('Check highlighted details','Every row needs a subject, positive credit hours, and a valid letter grade. Marks-only rows need you to choose the correct grade.');setSaving(true);try{await importSemesterSubjects(route.params.semesterId,valid);Alert.alert('Grades imported',`${valid.length} courses were saved.`,[{text:'Done',onPress:()=>navigation.goBack()}]);}catch{Alert.alert('Could not save grades','Nothing was imported. Please try again.');}finally{setSaving(false)}};return <Screen theme={theme}><Heading theme={theme} eyebrow="Check before saving">Review detected grades</Heading><Text style={{color:theme.colors.muted,lineHeight:19}}>Gemini can misread small text. Edit every field that looks wrong; marks are shown only as a hint and are never converted automatically.</Text>{rows.map((r,index)=><Card key={r.key} theme={theme}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{color:theme.colors.accent,fontWeight:'800'}}>COURSE {index+1}</Text><Pressable onPress={()=>setRows(rows.filter(x=>x.key!==r.key))}><Trash2 color={theme.colors.danger} size={18}/></Pressable></View><Input theme={theme} label="Subject" value={r.subject} onChangeText={subject=>update(r.key,{subject})}/><Input theme={theme} label="Credit hours" value={r.credit_hours} keyboardType="decimal-pad" onChangeText={credit_hours=>update(r.key,{credit_hours})}/>{r.marks?<Text style={{color:theme.colors.muted,fontSize:13}}>Detected marks: {r.marks}</Text>:null}<Text style={{color:theme.colors.text,fontWeight:'700'}}>Confirm grade</Text><GradeChoices theme={theme} selected={(r.grade in gradePoints?r.grade:null) as LetterGrade|null} onSelect={grade=>update(r.key,{grade})}/></Card>)}<Button theme={theme} label={saving?'Saving…':`Confirm & save ${rows.length} courses`} disabled={saving||!rows.length} onPress={()=>void confirm()}/><Button theme={theme} label="Cancel" variant="quiet" onPress={()=>navigation.goBack()}/></Screen>}
