import React, { ReactNode, useState } from 'react';
import { ActivityIndicator, KeyboardTypeOptions, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View, ViewStyle } from 'react-native';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { CalendarClock, Check, ChevronRight, Clock, X } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { AppTheme } from './theme';

export function Screen({ children, theme, scroll = true }: { children: ReactNode; theme: AppTheme; scroll?: boolean }) { const content = <View style={[styles.screen, { backgroundColor: theme.colors.background }]}>{children}</View>; return scroll ? <ScrollView contentContainerStyle={{ flexGrow: 1 }}>{content}</ScrollView> : content; }
export function Heading({ children, theme, eyebrow }: { children: ReactNode; theme: AppTheme; eyebrow?: string }) { return <View style={{ gap: 4 }}>{eyebrow && <Text style={[styles.eyebrow, { color: theme.colors.accent }]}>{eyebrow}</Text>}<Text style={[styles.heading, { color: theme.colors.text }]}>{children}</Text></View>; }
export function Card({ children, theme, style }: { children: ReactNode; theme: AppTheme; style?: ViewStyle }) { return <View style={[styles.card, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, style]}>{children}</View>; }
export function Button({ label, onPress, theme, variant = 'primary', disabled = false }: { label: string; onPress: () => void; theme: AppTheme; variant?: 'primary' | 'secondary' | 'quiet' | 'danger'; disabled?: boolean }) { const bg = variant === 'primary' ? theme.colors.accent : variant === 'secondary' ? theme.colors.surfaceSoft : variant === 'danger' ? '#F8DFDC' : 'transparent'; const color = variant === 'primary' ? '#fff' : variant === 'danger' ? theme.colors.danger : theme.colors.text; return <Pressable disabled={disabled} onPress={() => { Haptics.selectionAsync(); onPress(); }} style={({ pressed }) => [styles.button, { backgroundColor: bg, opacity: disabled ? .45 : pressed ? .78 : 1 }]}><Text style={[styles.buttonText, { color }]}>{label}</Text></Pressable>; }
export function Input({ label, value, onChangeText, theme, placeholder, multiline = false, secureTextEntry = false, keyboardType, style }: { label?: string; value: string; onChangeText: (s: string) => void; theme: AppTheme; placeholder?: string; multiline?: boolean; secureTextEntry?: boolean; keyboardType?: KeyboardTypeOptions; style?: any }) { return <View style={{ gap: 7 }}>{label ? <Text style={[styles.inputLabel, { color: theme.colors.text }]}>{label}</Text> : null}<TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={theme.colors.muted} secureTextEntry={secureTextEntry} multiline={multiline} keyboardType={keyboardType} style={[styles.input, multiline && { minHeight: 110, textAlignVertical: 'top' }, { color: theme.colors.text, backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, style]} /></View>; }
export function Row({ title, subtitle, right, theme, onPress }: { title: string; subtitle?: string | null; right?: ReactNode; theme: AppTheme; onPress?: () => void }) { const body = <><View style={{ flex: 1, gap: 3 }}><Text style={[styles.rowTitle, { color: theme.colors.text }]}>{title}</Text>{subtitle ? <Text style={[styles.rowSub, { color: theme.colors.muted }]}>{subtitle}</Text> : null}</View>{right ?? (onPress && <ChevronRight size={18} color={theme.colors.muted} />)}</>; return onPress ? <Pressable onPress={onPress} style={({pressed}) => [styles.row, { opacity: pressed ? .65 : 1 }]}>{body}</Pressable> : <View style={styles.row}>{body}</View>; }
export function Empty({ title, detail, theme }: { title: string; detail: string; theme: AppTheme }) { return <View style={[styles.empty, { borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceSoft }]}><View style={[styles.emptyMark, { backgroundColor: theme.colors.accentSoft }]}><Check size={27} color={theme.colors.accent} /></View><Text style={[styles.emptyTitle, { color: theme.colors.text }]}>{title}</Text><Text style={[styles.emptyDetail, { color: theme.colors.muted }]}>{detail}</Text></View>; }
export function Sheet({ visible, onClose, title, children, theme }: { visible: boolean; onClose: () => void; title: string; children: ReactNode; theme: AppTheme }) { return <Modal transparent animationType="slide" visible={visible} onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}/><View style={[styles.sheet, { backgroundColor: theme.colors.surface }]}><View style={[styles.handle, { backgroundColor: theme.colors.border }]} /><View style={styles.sheetHeader}><Text style={[styles.sheetTitle, { color: theme.colors.text }]}>{title}</Text><Pressable onPress={onClose}><X color={theme.colors.text} /></Pressable></View>{children}</View></Modal>; }
export function Loading({ theme }: { theme: AppTheme }) { return <View style={styles.loading}><ActivityIndicator color={theme.colors.accent}/><Text style={{color: theme.colors.muted}}>Bringing your study space together…</Text></View>; }

// Tap to open a native calendar, then a clock. Returns a full Date (or null when cleared).
export function DateField({ label, value, onChange, theme, placeholder = 'Pick a date & time', optional = true }: { label?: string; value: Date | null; onChange: (value: Date | null) => void; theme: AppTheme; placeholder?: string; optional?: boolean }) {
  const [stage, setStage] = useState<'idle' | 'date' | 'time'>('idle');
  const [draft, setDraft] = useState<Date | null>(null);
  const onDate = (event: DateTimePickerEvent, picked?: Date) => { if (event.type !== 'set' || !picked) { setStage('idle'); return; } setDraft(picked); setStage('time'); };
  const onTime = (event: DateTimePickerEvent, picked?: Date) => { setStage('idle'); if (event.type !== 'set' || !picked) return; const base = draft ?? value ?? new Date(); const combined = new Date(base); combined.setHours(picked.getHours(), picked.getMinutes(), 0, 0); onChange(combined); };
  return <View style={{ gap: 7 }}>{label ? <Text style={[styles.inputLabel, { color: theme.colors.text }]}>{label}</Text> : null}<View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><Pressable onPress={() => { Haptics.selectionAsync(); setStage('date'); }} style={[styles.input, { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><CalendarClock size={18} color={theme.colors.accent} /><Text style={{ color: value ? theme.colors.text : theme.colors.muted, fontSize: 15, flex: 1 }}>{value ? value.toLocaleString([], { weekday: 'short', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : placeholder}</Text></Pressable>{optional && value ? <Pressable onPress={() => onChange(null)} style={[styles.clearChip, { backgroundColor: theme.colors.surfaceSoft }]}><X size={16} color={theme.colors.muted} /></Pressable> : null}</View>{stage === 'date' ? <DateTimePicker value={value ?? new Date()} mode="date" onChange={onDate} /> : null}{stage === 'time' ? <DateTimePicker value={draft ?? value ?? new Date()} mode="time" is24Hour onChange={onTime} /> : null}</View>;
}

// Tap to open a native clock. Value/onChange use a "HH:MM" 24-hour string.
export function TimeField({ label, value, onChange, theme }: { label?: string; value: string; onChange: (value: string) => void; theme: AppTheme }) {
  const [open, setOpen] = useState(false);
  const toDate = (time: string) => { const parts = time.split(':'); const h = Number(parts[0] ?? 9); const m = Number(parts[1] ?? 0); const date = new Date(); date.setHours(Number.isFinite(h) ? h : 9, Number.isFinite(m) ? m : 0, 0, 0); return date; };
  const onPick = (event: DateTimePickerEvent, picked?: Date) => { setOpen(false); if (event.type !== 'set' || !picked) return; onChange(`${String(picked.getHours()).padStart(2, '0')}:${String(picked.getMinutes()).padStart(2, '0')}`); };
  return <View style={{ gap: 7, flex: 1 }}>{label ? <Text style={[styles.inputLabel, { color: theme.colors.text }]}>{label}</Text> : null}<Pressable onPress={() => { Haptics.selectionAsync(); setOpen(true); }} style={[styles.input, { flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Clock size={18} color={theme.colors.accent} /><Text style={{ color: theme.colors.text, fontSize: 15 }}>{value}</Text></Pressable>{open ? <DateTimePicker value={toDate(value)} mode="time" is24Hour onChange={onPick} /> : null}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, gap: 20 }, eyebrow: { fontSize: 11, letterSpacing: 1.25, fontWeight: '800', textTransform: 'uppercase' }, heading: { fontSize: 29, lineHeight: 34, fontWeight: '800', letterSpacing: -.7 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 12, shadowColor: '#202423', shadowOpacity: .06, shadowOffset: {width: 0, height: 5}, shadowRadius: 15, elevation: 2 }, button: { minHeight: 48, paddingHorizontal: 17, alignItems: 'center', justifyContent: 'center', borderRadius: 14 }, buttonText: { fontWeight: '800', fontSize: 15 }, inputLabel: { fontWeight: '700', fontSize: 13 }, input: { borderWidth: 1, borderRadius: 13, padding: 13, fontSize: 16 }, clearChip: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11 }, rowTitle: { fontWeight: '700', fontSize: 15 }, rowSub: { fontSize: 13, lineHeight: 18 }, empty: { alignItems: 'center', textAlign: 'center', padding: 27, gap: 8, borderRadius: 18, borderWidth: 1, borderStyle: 'dashed' }, emptyMark: { height: 54, width: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', marginBottom: 3 }, emptyTitle: { fontWeight: '800', fontSize: 16 }, emptyDetail: { textAlign: 'center', lineHeight: 19, fontSize: 13 }, backdrop: { flex: 1, backgroundColor: 'rgba(20,25,24,.42)' }, sheet: { maxHeight: '84%', minHeight: 220, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, gap: 16 }, handle: { width: 42, height: 5, borderRadius: 4, alignSelf: 'center' }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { fontSize: 20, fontWeight: '800' }, loading: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 } });
